Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import numpy as np
import calendar as cal
import matplotlib.pyplot as plt
import ipywidgets as widgets
import random
plt.ion()

import matplotlib.patches as mpatches
import datetime
%matplotlib ipympl
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 11[0m
[1;32m      9[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpatches[39;00m [38;5;28;01mas[39;00m [38;5;21;01mmpatches[39;00m
[1;32m     10[0m [38;5;28;01mimport[39;00m [38;5;21;01mdatetime[39;00m
[0;32m---> 11[0m get_ipython()[38;5;241m.[39mrun_line_magic([38;5;124m'[39m[38;5;124mmatplotlib[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mipympl[39m[38;5;124m'[39m)

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py:2456[0m, in [0;36mInteractiveShell.run_line_magic[0;34m(self, magic_name, line, _stack_depth)[0m
[1;32m   2454[0m     kwargs[[38;5;124m'[39m[38;5;124mlocal_ns[39m[38;5;124m'[39m] [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mget_local_scope(stack_depth)
[1;32m   2455[0m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39mbuiltin_trap:
[0;32m-> 2456[0m     result [38;5;241m=[39m fn([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m   2458[0m [38;5;66;03m# The code below prevents the output from being displayed[39;00m
[1;32m   2459[0m [38;5;66;03m# when using magics with decorator @output_can_be_silenced[39;00m
[1;32m   2460[0m [38;5;66;03m# when the last Python token in the expression is a ';'.[39;00m
[1;32m   2461[0m [38;5;28;01mif[39;00m [38;5;28mgetattr[39m(fn, magic[38;5;241m.[39mMAGIC_OUTPUT_CAN_BE_SILENCED, [38;5;28;01mFalse[39;00m):

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/IPython/core/magics/pylab.py:99[0m, in [0;36mPylabMagics.matplotlib[0;34m(self, line)[0m
[1;32m     97[0m     [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mAvailable matplotlib backends: [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m [38;5;241m%[39m backends_list)
[1;32m     98[0m [38;5;28;01melse[39;00m:
[0;32m---> 99[0m     gui, backend [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mshell[38;5;241m.[39menable_matplotlib(args[38;5;241m.[39mgui[38;5;241m.[39mlower() [38;5;28;01mif[39;00m [38;5;28misinstance[39m(args[38;5;241m.[39mgui, [38;5;28mstr[39m) [38;5;28;01melse[39;00m args[38;5;241m.[39mgui)
[1;32m    100[0m     [38;5;28mself[39m[38;5;241m.[39m_show_matplotlib_backend(args[38;5;241m.[39mgui, backend)

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3648[0m, in [0;36mInteractiveShell.enable_matplotlib[0;34m(self, gui)[0m
[1;32m   3644[0m         [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mWarning: Cannot change to a different GUI toolkit: [39m[38;5;132;01m%s[39;00m[38;5;124m.[39m[38;5;124m'[39m
[1;32m   3645[0m                 [38;5;124m'[39m[38;5;124m Using [39m[38;5;132;01m%s[39;00m[38;5;124m instead.[39m[38;5;124m'[39m [38;5;241m%[39m (gui, [38;5;28mself[39m[38;5;241m.[39mpylab_gui_select))
[1;32m   3646[0m         gui, backend [38;5;241m=[39m pt[38;5;241m.[39mfind_gui_and_backend([38;5;28mself[39m[38;5;241m.[39mpylab_gui_select)
[0;32m-> 3648[0m pt[38;5;241m.[39mactivate_matplotlib(backend)
[1;32m   3649[0m configure_inline_support([38;5;28mself[39m, backend)
[1;32m   3651[0m [38;5;66;03m# Now we must activate the gui pylab wants to use, and fix %run to take[39;00m
[1;32m   3652[0m [38;5;66;03m# plot updates into account[39;00m

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/IPython/core/pylabtools.py:368[0m, in [0;36mactivate_matplotlib[0;34m(backend)[0m
[1;32m    363[0m [38;5;66;03m# Due to circular imports, pyplot may be only partially initialised[39;00m
[1;32m    364[0m [38;5;66;03m# when this function runs.[39;00m
[1;32m    365[0m [38;5;66;03m# So avoid needing matplotlib attribute-lookup to access pyplot.[39;00m
[1;32m    366[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mimport[39;00m pyplot [38;5;28;01mas[39;00m plt
[0;32m--> 368[0m plt[38;5;241m.[39mswitch_backend(backend)
[1;32m    370[0m plt[38;5;241m.[39mshow[38;5;241m.[39m_needmain [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[1;32m    371[0m [38;5;66;03m# We need to detect at runtime whether show() is called by the user.[39;00m
[1;32m    372[0m [38;5;66;03m# For this, we wrap it into a decorator which adds a 'called' flag.[39;00m

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/matplotlib/pyplot.py:342[0m, in [0;36mswitch_backend[0;34m(newbackend)[0m
[1;32m    339[0m [38;5;66;03m# have to escape the switch on access logic[39;00m
[1;32m    340[0m old_backend [38;5;241m=[39m [38;5;28mdict[39m[38;5;241m.[39m[38;5;21m__getitem__[39m(rcParams, [38;5;124m'[39m[38;5;124mbackend[39m[38;5;124m'[39m)
[0;32m--> 342[0m module [38;5;241m=[39m importlib[38;5;241m.[39mimport_module(cbook[38;5;241m.[39m_backend_module_name(newbackend))
[1;32m    343[0m canvas_class [38;5;241m=[39m module[38;5;241m.[39mFigureCanvas
[1;32m    345[0m required_framework [38;5;241m=[39m canvas_class[38;5;241m.[39mrequired_interactive_framework

File [0;32m/opt/anaconda3/lib/python3.11/importlib/__init__.py:126[0m, in [0;36mimport_module[0;34m(name, package)[0m
[1;32m    124[0m             [38;5;28;01mbreak[39;00m
[1;32m    125[0m         level [38;5;241m+[39m[38;5;241m=[39m [38;5;241m1[39m
[0;32m--> 126[0m [38;5;28;01mreturn[39;00m _bootstrap[38;5;241m.[39m_gcd_import(name[level:], package, level)

File [0;32m<frozen importlib._bootstrap>:1204[0m, in [0;36m_gcd_import[0;34m(name, package, level)[0m

File [0;32m<frozen importlib._bootstrap>:1176[0m, in [0;36m_find_and_load[0;34m(name, import_)[0m

File [0;32m<frozen importlib._bootstrap>:1126[0m, in [0;36m_find_and_load_unlocked[0;34m(name, import_)[0m

File [0;32m<frozen importlib._bootstrap>:241[0m, in [0;36m_call_with_frames_removed[0;34m(f, *args, **kwds)[0m

File [0;32m<frozen importlib._bootstrap>:1204[0m, in [0;36m_gcd_import[0;34m(name, package, level)[0m

File [0;32m<frozen importlib._bootstrap>:1176[0m, in [0;36m_find_and_load[0;34m(name, import_)[0m

File [0;32m<frozen importlib._bootstrap>:1140[0m, in [0;36m_find_and_load_unlocked[0;34m(name, import_)[0m

[0;31mModuleNotFoundError[0m: No module named 'ipympl'

